# Generated by Django 3.1.1 on 2020-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200907_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=30)),
                ('doc_dob', models.CharField(max_length=30)),
                ('doc_age', models.CharField(max_length=30)),
                ('doc_gender', models.CharField(max_length=30)),
                ('doc_contact', models.CharField(max_length=30)),
                ('doc_email', models.EmailField(max_length=254)),
                ('doc_address', models.CharField(max_length=100)),
                ('doc_degree', models.CharField(max_length=30, null=True)),
                ('doc_desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.TimeField(default='', editable=False),
        ),
    ]
