# Generated by Django 3.1.1 on 2020-09-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200907_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_degree',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_desc',
            field=models.CharField(max_length=200),
        ),
    ]
