# Generated by Django 3.1.1 on 2020-09-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200914_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_photo',
            field=models.ImageField(max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='', editable=False),
        ),
    ]
