# Generated by Django 3.1.1 on 2020-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200917_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doc_photo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
