# Generated by Django 3.1.1 on 2020-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200917_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
