# Generated by Django 3.1.1 on 2020-09-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_patient_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
    ]
