# Generated by Django 3.1.1 on 2020-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
