# Generated by Django 3.1.1 on 2020-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.TextField(max_length=2048),
        ),
    ]
