# Generated by Django 3.1.1 on 2020-10-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201005_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='prescription',
            new_name='details',
        ),
    ]
