# Generated by Django 3.1.1 on 2020-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201005_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='details',
            field=models.TextField(default='Date:\nReason for visit:\nPrescription:\nTests:\nSummary:\nNext visit:', max_length=2048),
        ),
    ]
